### ISSUE TITLE
Авторизация пользователя

### ISSUE THREAD

**Issue by Megaremzik** [repetantil/web-file-storage#2]
- Ввод логина и пароля и проверка корректности ввода

- Восстановление пароля (подразумевает отправку на почту сообщения с ссылкой на страницу изменения пароля)

- Сохранение данных авторизации для данного компьютера

**Comment by LitovchenkoNatalja** [comment]
https://docs.microsoft.com/ru-ru/aspnet/core/security/authentication/social/index?view=aspnetcore-2.1

**Comment by LitovchenkoNatalja** [comment]
https://metanit.com/sharp/aspnet5/16.1.php

**Comment by Megaremzik** [comment]
[Валидация пользователя](https://metanit.com/sharp/aspnet5/16.10.php)
